# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-08 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(choices=[('M.', 'Monsieur'), ('Mme', 'Madame')], default='M.', max_length=3)),
                ('firstname', models.CharField(max_length=128)),
                ('lastname', models.CharField(max_length=128)),
                ('promotion', models.CharField(default='X2015', max_length=32)),
                ('group_type', models.CharField(blank=True, choices=[('Bar', 'Bar'), ('Binet', 'Binet'), ('Événement', 'Événement'), ('Association', 'Association')], max_length=32)),
                ('group', models.CharField(blank=True, max_length=128)),
                ('activity', models.TextField(blank=True, max_length=256)),
                ('is_active', models.BooleanField(default=False)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('previous_login', models.DateTimeField(auto_now_add=True)),
                ('current_login', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
