# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-17 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('subname', models.CharField(max_length=128)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('subname', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
                ('price', models.FloatField()),
                ('default_qtt', models.FloatField()),
                ('unit', models.CharField(blank=True, max_length=32)),
                ('undivisible', models.BooleanField(default=True)),
                ('available', models.CharField(choices=[('invisible', 'invisible'), ('available', 'disponible'), ('unavailable', 'non disponible')], default='available', max_length=32)),
                ('delivery', models.CharField(blank=True, choices=[('monday', 'lundi'), ('tuesday', 'mardi'), ('wednesday', 'mercredi'), ('thursday', 'jeudi'), ('friday', 'vendredi')], max_length=32)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('subname', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Supplier'),
        ),
    ]
